/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module singlePause_32 (
    input clk,
    input rst,
    output reg out,
    input start
  );
  
  
  
  reg [25:0] M_pause_d, M_pause_q = 27'h0000000;
  
  always @* begin
    M_pause_d = M_pause_q;
    
    if (start) begin
      M_pause_d = M_pause_q + 1'h1;
    end else begin
      M_pause_d = 27'h0000000;
    end
    out = M_pause_q[25+0-:1];
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_pause_q <= 27'h0000000;
    end else begin
      M_pause_q <= M_pause_d;
    end
  end
  
endmodule
