/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module timeKeeper_9 (
    input clk,
    input rst,
    output reg out,
    input start,
    input [5:0] moleNumber,
    output reg timeUp
  );
  
  
  
  always @* begin
    out = 1'h0;
    if (start == 1'h1 && moleNumber >= 6'h3c) begin
      timeUp = 1'h1;
    end else begin
      timeUp = 1'h0;
    end
  end
endmodule
